global:
  namespace: foodgram
  host: foodgram.local
  tls:
    enabled: true
    secretName: foodgram-tls

backend:
  enabled: true
  image: elizavetanovozhilova/foodgram-backend:v1.0
  replicas: 1
  service:
    type: NodePort
    port: 8000
    nodePort: 30082
  env: {}
  secretName: foodgram-secrets

frontend:
  enabled: true
  image: elizavetanovozhilova/foodgram-frontend:v1.0
  replicas: 1
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  nginx:
    serverName: localhost

postgres:
  enabled: true
  image: postgres:14
  storageSize: 2Gi
  service:
    port: 5432
  secretName: foodgram-secrets

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

secrets:
  POSTGRES_PASSWORD: ref+vault://secret/foodgram/database#POSTGRES_PASSWORD
