apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  DB_ENGINE: "django.db.backends.postgresql"
  POSTGRES_DB: "foodgram"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DJANGO_SECRET_KEY: {{ .Values.secrets.DJANGO_SECRET_KEY | quote }}
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,nginx,{{ .Values.global.host }},*"
  CSRF_TRUSTED_ORIGINS: "http://{{ .Values.global.host }}"
