apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  selector: { app: backend }
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
